app/crews/forms.py
from flask_wtf.form import FlaskForm
from flask_login import current_user
from app.characters.forms import MultiCheckBoxField
from wtforms.fields import StringField, SubmitField, BooleanField, SelectField
from wtforms.validators import InputRequired, DataRequired, Length


class CrewForm(FlaskForm):
    name = StringField("Crew Name: ", 
                        validators=[
                            InputRequired("Your crew must have a name"),
                            DataRequired("Your crew's name cannot be blank")
                        ])
    preferences = MultiCheckBoxField("Preferences: ", choices=[("action",'Action'), ("adventure",'Adventure'), ("side-quests",'Side Quests'), ("character-driven","Character Driven"), ("plot-driven",'Plot Driven')])
    seeking = BooleanField("Looking for new crew members?")
    submit = SubmitField("Create Crew")


class RequestForm(FlaskForm):
    
    character_id = SelectField("Character", choices=[(None, "Select a character")], validators=[
        InputRequired("You must select a character")
    ])
    message = StringField("Message: ", validators=[
    InputRequired("You must submit a message."),
    DataRequired("You must submit a message"),
    Length(message="Your message must be between 10 and 255 characters long", min=10, max=255)
    ])
    submit = SubmitField("Submit Request")

app/crews/views.py
from flask import Blueprint, render_template, url_for, redirect, current_app, request as req
from flask.helpers import flash
from flask_login import login_required, current_user
from app.models import Crew, Request
from app.crews.forms import CrewForm, RequestForm
from app import db
import json

crew = Blueprint('crew', __name__, template_folder="templates")
app = current_app

@crew.route('/create', methods=["GET", "POST"])
@login_required
def add_crew():
    form = CrewForm()

    if form.validate_on_submit():

        name = form.name.data
        crew_exists = Crew.query.filter_by(name=name).first()
        if crew_exists:
            flash("That Crew name is taken. Please use a different one.")
        else:
            seeking = form.seeking.data
            owner_id = current_user.user_id

            preferences = form.preferences.data
            preferences_int = 0
            if 'action' in preferences:
                preferences_int += 16
            if "adventure" in preferences:
                preferences_int += 8
            if 'side-quests' in preferences:
                preferences_int += 4
            if 'character-driven' in preferences:
                preferences_int += 2
            if 'plot-driven' in preferences:
                preferences_int += 1

            new_crew = Crew(owner_id, name, seeking, preferences_int)

            db.session.add(new_crew)
            db.session.commit()

            return redirect(url_for("users.user_profile", username=current_user.username))
    
    return render_template("add_crew.html", form=form)


@crew.route('/search/<char_prefs>')
def search(char_prefs=0):
    char_prefs = int(char_prefs)
    def pref_order(item):
        key = bin(int(char_prefs))[2:]
        search = bin(item.preferences)[2:]
        count_same = 0
        langth = min(len(key), len(search))
        for i in range(-1, -1-langth, -1):
            if key[i] == search[i]:
                count_same += 1
        return bin(item.preferences ^ char_prefs).count('1') - count_same
    crews = Crew.query.filter(Crew.seeking==True, Crew.owner_id != current_user.user_id).order_by(Crew.preferences)
    crews = sorted(crews, key=pref_order)
    return render_template('search_crews.html', crews=crews, pref=char_prefs)


@crew.route('/send_request/<crew_id>', methods=['GET', 'POST'])
@login_required
def send_request(crew_id):
    form = RequestForm()
    chars = [(str(char.character_id), char.name) for char in current_user.characters if not char.crew]
    form.character_id.choices = chars

    if form.validate_on_submit():
        new_request = Request(crew_id, form.character_id.data, form.message.data)
        db.session.add(new_request)
        db.session.commit()
        flash("Request successfully sent")
        return redirect(url_for('users.user_profile', username=current_user.username))
    
    return render_template('send_request.html', form=form)


@crew.route('/view_crew/<crew_id>')
def view_crew(crew_id):
    crew = Crew.query.get(crew_id)
    if crew:
        return render_template('view_crew.html', crew=crew)
    else:
        flash("That crew doesn't exist")
        return redirect(url_for('main.home'))


@crew.route('/requests/<request_id>', methods=['GET', 'PUT', 'DELETE'])
def get_request_message(request_id):
    my_request = Request.query.get(request_id)
    if my_request:
        if req.method == "PUT":
            my_request.character.crew_id = my_request.crew.crew_id
            db.session.delete(my_request)
        elif req.method == "DELETE":
            db.session.delete(my_request)
        else:
            return json.dumps(my_request.message)

        db.session.commit()
        return json.dumps({'success':True}), 200, {'ContentType':'application/json'}

    return json.dumps({'success':False}), 400, {'ContentType':'application/json'}

app/crews/templates/add_crew.html
{% extends "base.html" %}

{% block title %}Create New Crew{% endblock %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        <h2>Create a New Crew</h2>
        {{ form.name.label }}<br>
        {{ form.name }}
        {% if form.name.errors %}
            <ul>
                {% for error in form.name.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <br>
        {{ form.preferences.label }}<br>
        {% for choice in form.preferences %}
            {{ choice }}
            {{ choice.label }}
            <br>
        {% endfor %}
        {% if form.preferences.errors %}
            <ul>
                {% for error in form.preferences.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <br>
        {{ form.seeking.label }}
        {{ form.seeking(checked=True) }}
        <br>
        {{ form.submit(class='submit') }}
    </form>
{% endblock %}

app/crews/templates/search_crews.html
{% extends "base.html" %}
{% from '_macros.html' import show_prefs %}

{% block title %}Crew Search{% endblock %}

{% block content %}
    <div>
        <ul>
            Searching for crews to match: {{ show_prefs(pref) }}
        </ul>
    </div>
    <div>
        {% for crew in crews %}
            <p><a href="{{ url_for('crew.view_crew', crew_id=crew.crew_id) }}">{{ crew.name }}</a> | {{ show_prefs(crew.preferences) }} <a href="{{ url_for('crew.send_request', crew_id=crew.crew_id) }}">Request to Join</a></p>
        {% endfor %}
    </div>

{% endblock %}

app/crews/templates/send_request.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ form.message.label }}
        {{ form.message }}
        {{ form.character_id.label}}
        {{ form.character_id }}
        {{ form.submit }}
    </form>

{% endblock %}

app/crews/templates/view_crew.html
{% extends "base.html" %}

{% block title %}{{ crew.name }}{% endblock %}

{% block content %}
    <div>
        <h3>{{ crew.name }}</h3>
        {% if crew.characters %}
        <ul>
            {% for member in crew.characters %}
            <li>{{ member.name }} - {{ member.creator.username }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% if current_user.user_id == crew.owner_id %}
    <aside id='sidebar'>
        <div>
            Requests
            {% if crew.requests %}
            <ul id='requests'>
                {% for request in crew.requests %}
                    <li>
                        {{ request.character.name }}: "{{ request.message|truncate(15, True) }}"
                        <button onclick='displayInfo({{ request.request_id }})'>See More</button>
                        <button onclick='acceptRequest({{ request.request_id }})'>Accept</button>
                        <button onclick='declineRequest({{ request.request_id }})'>Decline</button>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <p>You currently have no pending requests</p>
            {% endif %}
        </div>
    </aside>
    {% endif %}
    <script>
        get_more_info = function() {
            if (this.readyState == 4 && this.status == 200) {
                moreInfo = document.createElement('span')
                message = eval(this.response)
                console.log(message)
                moreInfo.textContent = message
                delBut = document.createElement('button')
                delBut.textContent = "Close"
                delBut.addEventListener('click', (event) => {
                    event.target.parentNode.remove()
                })
                moreInfo.appendChild(delBut)
                document.querySelector('body').appendChild(moreInfo)
            }
        }

        function displayInfo(id) {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = get_more_info
            xhttp.open("GET", `/crew/requests/${id}`, true)
            xhttp.send()
        }

        removeListItem = function(obj) {
            obj.parentNode.remove()
        }

        acceptRequest = function(id) {
            removeListItem(event.target)
            let xhttp = new XMLHttpRequest();
            xhttp.open("PUT", `/crew/requests/${id}`, true)
            xhttp.send()
        }

        declineRequest = function(id) {
            removeListItem(event.target)
            let xhttp = new XMLHttpRequest();
            xhttp.open("DELETE", `/crew/requests/${id}`, true)
            xhttp.send()
        }
    </script>
{% endblock %}