app/users/views.py
from flask import Blueprint, render_template, redirect, flash, url_for
from flask_login import current_user
from app.models import User


users = Blueprint('users', __name__, template_folder="templates")


@users.route("/profile/<username>")
def user_profile(username):
    if current_user == User.query.filter_by(username=username).first():

        return render_template("profile.html")
    else:
        flash("You do not have permission to view that page")
        return redirect(url_for("main.home"))

app/templates/_macros.html
{% macro show_prefs(prefs) %}
    {% with sixteen = prefs // 16 %}
    {% with sixteen_r = prefs % 16 %}
    {% with eight = sixteen_r // 8 %}
    {% with eight_r = sixteen_r % 8 %}
    {% with four = eight_r // 4 %}
    {% with four_r = eight_r % 4 %}
    {% with two = four_r // 2 %}
    {% with two_r = four_r % 2 %}
    {% with one = two_r %}
        {% if sixteen %}Action {% endif %}
        {% if eight %}Adventure {% endif %}
        {% if four %}Side-Quests {% endif %}
        {% if two %}Character-Driven {% endif %}
        {% if one %}Plot-Driven {% endif %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
    {% endwith %}
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header id='header'>
        <h3><a href="/">Unofficial MAG Character Creator</a></h3>
        <div id='nav_links'>
            {% if not current_user.is_authenticated %}<a href="{{ url_for('auth.register') }}">Register</a> | <a href="{{ url_for('auth.login') }}">Log In</a>
            {% else %}<a href="{{ url_for('users.user_profile', username=current_user.username) }}">{{ current_user.username }}</a> | <a href="{{ url_for('auth.logout') }}">Log Out</a>
            {% endif %}
        </div>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
    <script>
        buts = document.querySelectorAll('.flashes>li')
        if (buts) {
            buts.forEach(elem => {
                elem.addEventListener('click', () => {
                    elem.remove()
                })
            });
        }
    </script>
</body>
</html>

app/templates/generic_template.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}

{% endblock %}